### ISSUE TITLE
Add a Dark mode toggle button

### ISSUE THREAD

**Issue by Ritwik880** [CodeTrophs/Frontend#230]
before applying dark mode:
![Screenshot from 2020-09-28 20-30-56](https://user-images.githubusercontent.com/54446880/94449323-9680a680-01c9-11eb-825a-1d0fb703b38a.png)

After applying dark mode:
![Screenshot from 2020-09-28 20-30-35](https://user-images.githubusercontent.com/54446880/94449353-a0a2a500-01c9-11eb-81cb-4771c5265441.png)

**Comment by vipulsnp** [comment]
@Ritwik880 Are you working on this?

**Comment by Ritwik880** [comment]
yes almost done

**Comment by vipulsnp** [comment]
Updates @Ritwik880 .

**Comment by baris5d** [comment]
It would be better to make "Sign in with GitHub" button white in dark theme. It can make it more visible.

**Comment by vipulsnp** [comment]
@Ritwik880 Keep this suggestion also. 

> It would be better to make "Sign in with GitHub" button white in dark theme. It can make it more visible.

**Comment by Ritwik880** [comment]
> @Ritwik880 Keep this suggestion also.
> 
> > It would be better to make "Sign in with GitHub" button white in dark theme. It can make it more visible.

okay

**Comment by vipulsnp** [comment]
@Ritwik880 what are your updates on the issue?

**Comment by Ritwik880** [comment]
> @Ritwik880 what are your updates on the issue?

Giving final touch

**Comment by vipulsnp** [comment]
Updates?

**Comment by vipulsnp** [comment]
@Ritwik880 Have you completed it?

**Comment by Ritwik880** [comment]
@vipulsnp actually i am facing some trouble in the testimonial section and i am trying to resolve that as soon as possible.

**Comment by vipulsnp** [comment]
What problem are you facing on that one? @Ritwik880

**Comment by vipulsnp** [comment]
@Ritwik880 What are your updates on this one?

**Comment by sonylomo** [comment]
Hey @vipulsnp, can I try helping out on this?

**Comment by vipulsnp** [comment]
Sure @sonylomo

**Comment by SiddheshShinde-tech** [comment]
Hey @vipulsnp, can I work on this?

**Comment by vipulsnp** [comment]
@SiddheshShinde-tech There is already a contributor assigned for it.

**Comment by sonylomo** [comment]
@vipulsnp should the dark theme be applied on the home page and navabar only, or the rest of the site too?

**Comment by irshadjsr21** [comment]
@sonylomo You can look into other issues to work on. The dark theme will be implemented after we migrate to the new design.
