### ISSUE TITLE
Components load before checking auth

### ISSUE THREAD

**Issue by baris5d** [CodeTrophs/Frontend#246]
Authorized pages are redirecting after components loaded. I see the feed, organization and starred repository pages without signing in. The same goes for landing page when I'm not signed in.

**Comment by vipulsnp** [comment]
You can work on this. @baris5d .

**Comment by vipulsnp** [comment]
Are you working on this @baris5d

**Comment by baris5d** [comment]
I cannot work on this for next couple days. I'll take it when I'll be available if it won't be taken.

**Comment by DhrutikPatel** [comment]
Hello, @vipulsnp Can I work on it?

**Comment by vipulsnp** [comment]
@DhrutikPatel Go Ahead

**Comment by garvitgupta13** [comment]
Hey, @vipulsnp  please describe this issue in detail. I tried to open /feed page but its component loaded after authorization. 
I am gssoc21 participant, if this bug is still there at any other link, please let me know, I will try to fix it

**Comment by msk4862** [comment]
@baris5d @vipulsnp @garvitgupta13 I think the bug fixed now.

**Comment by msk4862** [comment]
I'm closing the issue as its fixed now.
