### ISSUE TITLE
In mobile view 'sign in with github' button overlap the bottom image

### ISSUE THREAD

**Issue by Abhijay007** [CodeTrophs/Frontend#267]
**Describe the bug**

when the user switch to mobile view the sign in with Github button overlaps the bottom image

**Current behavior**

 ![current](https://user-images.githubusercontent.com/64387054/103416259-e053a100-4bab-11eb-9c0c-e91fcec1a8c6.PNG)

**Expected behaviour**

  ![expected](https://user-images.githubusercontent.com/64387054/103416265-e47fbe80-4bab-11eb-91fd-da1903d80964.PNG)
  
**Desktop (please complete the following information):**
 - OS: windows
 - Browser :chorme

**Smartphone (please complete the following information):**
 - Device: iPhone6//8
 - OS: iOS
 - Browser : chrome inspect mode

**Additional context**

can I work on this?

**Comment by irshadjsr21** [comment]
Closing this because there is going to be a complete redesign of the frontend in which these issues will be fixed.
