### ISSUE TITLE
Footer Redesigned

### ISSUE THREAD

**Issue by Abhijay007** [CodeTrophs/Frontend#268]
**Is your feature request related to a problem? Please describe.**
 I redesigned the footer part of the site because it looks a bit less responsive and expressive in web and mobile view as well.

**Describe the solution you'd like**

***before-web view***

![before-web](https://user-images.githubusercontent.com/64387054/103440518-5c152280-4c6c-11eb-95d1-a7b8258a039b.PNG)

***after-web view***

![after-web](https://user-images.githubusercontent.com/64387054/103440524-659e8a80-4c6c-11eb-91ef-918b994d24ec.PNG)

***before-mobile view***

![before-mobile](https://user-images.githubusercontent.com/64387054/103440531-73541000-4c6c-11eb-8b99-1591d8ed7225.PNG)

***before-mobile view***

![after-mobile](https://user-images.githubusercontent.com/64387054/103440536-7f3fd200-4c6c-11eb-91bc-3e78090d1958.PNG)

**Comment by Abhijay007** [comment]
> **Is your feature request related to a problem? Please describe.**
> I redesigned the footer part of the site because it looks a bit less responsive and expressive in web and mobile view as well.
> 
> **Describe the solution you'd like**
> 
> _**before-web view**_
> 
> ![before-web](https://user-images.githubusercontent.com/64387054/103440518-5c152280-4c6c-11eb-95d1-a7b8258a039b.PNG)
> 
> _**after-web view**_
> 
> ![after-web](https://user-images.githubusercontent.com/64387054/103440524-659e8a80-4c6c-11eb-91ef-918b994d24ec.PNG)
> 
> _**before-mobile view**_
> 
> ![before-mobile](https://user-images.githubusercontent.com/64387054/103440531-73541000-4c6c-11eb-8b99-1591d8ed7225.PNG)
> 
> _**before-mobile view**_
> 
> ![after-mobile](https://user-images.githubusercontent.com/64387054/103440536-7f3fd200-4c6c-11eb-91bc-3e78090d1958.PNG)

can I work on this?

**Comment by Abhijay007** [comment]
can I work on this?

**Comment by irshadjsr21** [comment]
Closing this because there is going to be a complete redesign of the frontend in which these issues will be fixed.

@Abhijay007 I'll be opening some new issues to redesign the pages in a couple of days, you can work on those.
