### ISSUE TITLE
Readme Dosent say much about the project

### ISSUE THREAD

**Issue by pappyJ** [CodeTrophs/Frontend#270]
Readme  Dosent Describe The Project Very Well Making it hard to know the total purpose of the project at a glance

Updtate project readme file

**Comment by pappyJ** [comment]
I wouldn't mind working on this ticket if assigned.

**Comment by irshadjsr21** [comment]
Sure, go ahead. You can find more details about the project on the Wiki page.

**Comment by pappyJ** [comment]
ok sir thanks

**Comment by aryan040501** [comment]
@irshadjsr21 I think this issue has not been solved yet. I would love to work on this under SWOC program!

**Comment by irshadjsr21** [comment]
@aryan040501 Thank you for showing interest in the project, however, this project is no longer under SWOC. But you can still contribute to it if you wish.

**Comment by aryan040501** [comment]
@irshadjsr21 I am sorry sir, currently I am fully devoted to SWOC. Will surely contribute once SWOC is over. Thanks a lot

**Comment by Arshanshagarwal** [comment]
I would like to contribute to this issue as a part of GSSOC'21. Please assign it to me.

**Comment by msk4862** [comment]
@Arshanshagarwal Sure go ahead!
You can take help from project's [Wiki](https://github.com/CodeTrophs/Frontend/wiki) page to know more about the project.
