### ISSUE TITLE
Redesign the Landing Page

### ISSUE THREAD

**Issue by irshadjsr21** [CodeTrophs/Frontend#273]
Create a landing page with the new design as shown in [this](https://www.figma.com/file/uDe6yuBw961ISTg6gYL9AO/CodeTrops-Feed-pages?node-id=6%3A192) Figma file.

**Comment by sonylomo** [comment]
I'm on this.

**Comment by RituCs** [comment]
I would like to contribute on this .Please assign me.

**Comment by aryasoni98** [comment]
Yes sure @RituCs

**Comment by bhubesh757** [comment]
@aryasoni98 @irshadjsr21 I will Join with this contribution , so it might solve the issue soon @RituCs Can i Join 
Is this not under the guidelines @alizahir23 @irshadjsr21

**Comment by RituCs** [comment]
@bhubesh757 You can work on this issue.Now I am working some other issue.

**Comment by bhubesh757** [comment]
@irshadjsr21 Assing this to me

**Comment by bhubesh757** [comment]
@aryasoni do i need to code for the design or i need to make new design

**Comment by aryasoni98** [comment]
@bhubesh757 No , You don't need to make new design . [Figma File ](https://www.figma.com/file/dzND8YXSRqhtAYYjEKSAm1/CodeTrophs?node-id=0%3A1) Check Figma File .

**Comment by bhubesh757** [comment]
@aryasoni98 Unable to grab the files and images from the landing but i can grab it from footer i work make easy right , can please send me the whole figma file of landing page whhich can be grab the content

**Comment by bhubesh757** [comment]
@aryasoni98 Reply to this !!

**Comment by aryasoni98** [comment]
@bhubesh757 landing page already redesign . ￼
