### ISSUE TITLE
Add Fork Feature

### ISSUE THREAD

**Issue by pappyJ** [CodeTrophs/Frontend#274]
Adding fork feature to the project would be a plus to the project 

since users can see a project , see the stack , number of stars  and can even star it ...

Giving them the privilege to fork the project they are interested in would be a great feature to have

One you click the fork button , it forks the project

**Comment by PushkarDureja** [comment]
I would like to solve this issue. Can you please assign  it to me ?

**Comment by aryasoni98** [comment]
Yes sure @PushkarDureja start working
