### ISSUE TITLE
Change HTML lang to English

### ISSUE THREAD

**Issue by irshadjsr21** [CodeTrophs/Frontend#277]
Currently, the HTML lang is set to `id`, change it to `en`.

**Comment by 96RadhikaJadhav** [comment]
@irshadjsr21  I could see the HTML language is already set to "en" in pages\_document.jsx file at line 12.
If it needs to be set anywhere else, please let me know.

**Comment by irshadjsr21** [comment]
Hi, thanks for confirming. The issue seems to be fixed in the latest update.
