### ISSUE TITLE
On the Setting page after giving details about you there can be a save and next button that redirects you to the social section

### ISSUE THREAD

**Issue by nandini2110** [CodeTrophs/Frontend#288]
Save and next button is a feature that I would like to work on that would redirect the user to the Socials section
Could you please assign this to me as a GSSOC'21 participant?

**Comment by aryasoni98** [comment]
Yes sure , @nandini2110

**Comment by msk4862** [comment]
@nandini2110 What's the progress?

**Comment by sahildotexe** [comment]
Hello , I'm GSSOC'21 participant.I am a MERN Stack developer. Can you assign me this issue?

**Comment by msk4862** [comment]
@sahildotexe Go ahead!

**Comment by aryasoni98** [comment]
@sahildotexe Any Update ?

**Comment by srrathi** [comment]
@msk4862 Can I work on this issue?

**Comment by msk4862** [comment]
@srrathi Sure! Go ahead.

**Comment by srrathi** [comment]
@msk4862 @aryasoni98 Do I've to change something in it or should I send the PR.

**Comment by msk4862** [comment]
@srrathi Go ahead and create a PR.

**Comment by srrathi** [comment]
@msk4862 I've raised the PR please review it.
