### ISSUE TITLE
Improve the search field/component 

### ISSUE THREAD

**Issue by Anurag5086** [CodeTrophs/Frontend#289]
The search field on the feed, organization and Starred Repositories Page is not going well with the color theme of the website. Also the placeholder text is not visible.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to Feed/Organization/Starred Repositories Page
2. See the Search field

**Expected behaviour**

Having a better search component which goes along with the color scheme of the website and the placeholder text is clear.

**Screenshots**

![image](https://user-images.githubusercontent.com/54763478/110964573-bfa68500-836c-11eb-9c5c-7220a1087241.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome

**Comment by saikeshari** [comment]
I want to work on this as part of GSSoc'21. Please add appropriate tags and assign it to me so that I can start working.

**Comment by Anurag5086** [comment]
> I want to work on this as part of GSSoc'21. Please add appropriate tags and assign it to me so that I can start working.

Cool. Go ahead.

**Comment by aryasoni98** [comment]
@saikeshari Strat working on it .
