### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [CodeTrophs/Frontend#292]
Hey! I would like to add the following in contributing.md
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by aryasoni98** [comment]
Nice one . Start Working on it . @khareyash05

**Comment by khareyash05** [comment]
On it @aryasoni98

**Comment by khareyash05** [comment]
Could you also pls add a level label to the same @aryasoni98

**Comment by khareyash05** [comment]
@msk4862 Could you pls add a level label to the issue as easy/medium labels arent being considered in GSSOC
