### ISSUE TITLE
Getting error in running npm install

### ISSUE THREAD

**Issue by chauhanprakhar** [CodeTrophs/Frontend#294]
I'm getting some error when installing dependencies by running "npm install". Is there anyone who is facing the same issue or is there any problem with my node setup.
![image](https://user-images.githubusercontent.com/54539712/111028345-15863600-841c-11eb-9db8-f2641b608ad9.png)

**Comment by Anurag5086** [comment]
Upgrade node-sass to the latest version. This might fix the issue. @chauhanprakhar 

> `npm install node-sass`

**Comment by Anurag5086** [comment]
@chauhanprakhar is it fixed for you?

**Comment by Anurag5086** [comment]
@chauhanprakhar is the issue solved?

**Comment by chauhanprakhar** [comment]
No upgrading node-sass is not fixing this error @Anurag5086
