### ISSUE TITLE
fix node.js CI/build 

### ISSUE THREAD

**Issue by Anurag5086** [CodeTrophs/Frontend#295]
Refer changes in commit a0cd9a0aeb2ed8dc635eedb3f6e290c90b908a1f

![image](https://user-images.githubusercontent.com/54763478/111038545-1aaaab80-8443-11eb-8ec5-4a8067015140.png)

**Comment by msk4862** [comment]
@Anurag5086 add level label too.

**Comment by saikeshari** [comment]
I fixed this in my PR.
The emoji was to be enclosed in span with suitable properties

**Comment by Anurag5086** [comment]
#298
