### ISSUE TITLE
Improve the settings options/component

### ISSUE THREAD

**Issue by pinkman7009** [CodeTrophs/Frontend#296]
**Description**

The About You and Socials buttons on the Settings page have a very light placeholder text on select, which can be made bolder.

**To Reproduce**

Steps to reproduce the behaviour:

1. After signing in, click on the username and click on Settings to go to the Settings page.
2. The About you and Socials buttons should be visible and on select, have a very light placeholder text.

**Expected behaviour**

The buttons should have a placeholder text which is visible on select, and can be done by making the text bolder.

**Screenshots**

![profile](https://user-images.githubusercontent.com/52635583/111074436-eac5db80-8508-11eb-843d-756a7e7a22fb.png)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome

**Comment by rajesh6161** [comment]
I saw the issue on the settings page and I want to handle this issue @pinkman7009

**Comment by pinkman7009** [comment]
Yes sure go ahead with this @rajesh6161.

**Comment by romasinha** [comment]
Can I work on this issue too @rajesh6161?

**Comment by rajesh6161** [comment]
Yes sure @romasinha but I already did the PR that will resolve this issue

**Comment by Anurag5086** [comment]
@pinkman7009 is this issue a Level1?

**Comment by pinkman7009** [comment]
@Anurag5086 yes it is a small code change similar to your Search component one so I labelled it as level 1.

**Comment by Anurag5086** [comment]
> @Anurag5086 yes it is a small code change similar to your Search component one so I labelled it as level 1.

Okay alright, i thought changing the whole setting page component. @pinkman7009
