### ISSUE TITLE
Redesign Footer Section 

### ISSUE THREAD

**Issue by aryasoni98** [CodeTrophs/Frontend#302]
![Footer Part](https://user-images.githubusercontent.com/18515597/111307724-dce69680-867f-11eb-9547-0a1422de8211.png)

Contact Us ( Social URL ) :

LinkedIn : https://www.linkedin.com/company/codetrophs/
Github : https://github.com/CodeTrophs
Facebook : https://www.facebook.com/codetrophs
Discord : https://discord.gg/urV8vGk

Footer Assest : https://drive.google.com/drive/folders/14RvbpwViIdoVJsKPSfBrxXpF1PMH3oDR?usp=sharing

**Comment by saikeshari** [comment]
I want to work on this issue. Please assign this to me.

**Comment by aryasoni98** [comment]
@saikeshari Go Head 👌🏻

**Comment by saikeshari** [comment]
The links of 3 pages and other details in the center are not included in the footer, So I should go ahead like this only?

![image](https://user-images.githubusercontent.com/68103466/111353451-547deb00-86ab-11eb-9c15-967497749ebc.png)

**Comment by aryasoni98** [comment]
@saikeshari Go head like this . Just edit the content part .

**Comment by msk4862** [comment]
@saikeshari what's the progress?

**Comment by sheetalj2205** [comment]
Can I work on this issue?

**Comment by pinkman7009** [comment]
Sure go ahead

**Comment by aryasoni98** [comment]
@sheetalj2205 Any Update

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Any Update

Yes! I will make the PR on monday

**Comment by aryasoni98** [comment]
@sheetalj2205 Any Update ?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Any Update ?

please wait till monday.

**Comment by sheetalj2205** [comment]
I am not able to find icon for discord

**Comment by msk4862** [comment]
Fixed by #330
