### ISSUE TITLE
#want to add Navigation bar in the header

### ISSUE THREAD

**Issue by sheetalj2205** [CodeTrophs/Frontend#303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

As the website doesn't have a Nav bar in the header. I want to add all the links of footer in the nav bar also.

**Additional context**

**Comment by msk4862** [comment]
@sheetalj2205 wants to take this issue?

**Comment by ANSHIKA1806** [comment]
@aryasoni98 @Anurag5086 @pinkman7009 
Hello sir/mam, I want to work on this issue ,please assign this issue to me. I would to contribute in your organization.
Thank you.

**Comment by sheetalj2205** [comment]
@aryasoni98 @Anurag5086 @pinkman7009  
Hello  Sir/Ma'am, I have made this issue and I want to work on this for GSSoC'21.

**Comment by sheetalj2205** [comment]
> @sheetalj2205 wants to take this issue?

Yes! I want to work on this for GSSoC'21

**Comment by msk4862** [comment]
@sheetalj2205 go ahead.

**Comment by msk4862** [comment]
@ANSHIKA1806 you can check out other issues.

**Comment by Anurag5086** [comment]
@sheetalj2205 What's the progress?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 What's the progress?

Working on it , I need 2-3 days more.

**Comment by pinkman7009** [comment]
@Anurag5086 it is fine, she is having some issues so I am helping her out.

**Comment by sheetalj2205** [comment]
While committing
![issue303](https://user-images.githubusercontent.com/64475191/113514969-3eb76380-958f-11eb-94e9-e5c695df82fc.JPG)
 I am facing this issue. I am not able to commit.

**Comment by pinkman7009** [comment]
Not sure why this issue might be occurring. @Anurag5086 @msk4862 can you take a look into this?

**Comment by msk4862** [comment]
@sheetalj2205 looks like `href` attribute is missing in `a` tags you have added.

**Comment by Anurag5086** [comment]
@sheetalj2205 and in the `RightNavbar.jsx` component, the `Open` prop is not being validated.
