### ISSUE TITLE
Donate Option does not lead anywhere

### ISSUE THREAD

**Issue by umamanasir** [CodeTrophs/Frontend#306]
**Describe the bug**
The donate option does not lead anywhere on the webpage or provide any relevant information. 
I can add a feature so that it lands on a page which says the option the feature will be available soon or provides more information for donation. 

I am a GSSoC '21 Participant.

**Comment by msk4862** [comment]
@umamanasir go ahead!

**Comment by aryasoni98** [comment]
@umamanasir Any Update ?

**Comment by umamanasir** [comment]
> @umamanasir Any Update ?

working on it. I had a confusion so I have reached out to a mentor on Discord.

**Comment by msk4862** [comment]
@umamanasir what's the progress?

**Comment by anniesaxena** [comment]
Hi, can I work on this issue please?

**Comment by aryasoni98** [comment]
@anniesaxena Yes, Sure Go Head
