### ISSUE TITLE
Inserting icon for contact purpose.

### ISSUE THREAD

**Issue by neha-baisane** [CodeTrophs/Frontend#307]
Inserting the social media icon list on the page at the right side of the page .
As GSSOC'21 participant i would like to work on this issue please assign me.

![trophissue](https://user-images.githubusercontent.com/64725427/113563772-eaab8e00-9625-11eb-9c49-2c9a5fdcc4a6.png)

**Comment by aryasoni98** [comment]
@neha-baisane Go Head

**Comment by aryasoni98** [comment]
@neha-baisane Any Update ?

**Comment by neha-baisane** [comment]
couldn't install npm file

**Comment by aryasoni98** [comment]
What kind of error you are facing￼

**Comment by msk4862** [comment]
@neha-baisane what's the progress?

**Comment by sheetalj2205** [comment]
I want to work on this issue but can you please explain briefly what changes you want?

**Comment by msk4862** [comment]
![addthis-social-sharing-button-widget](https://user-images.githubusercontent.com/24875366/116395601-f152ad00-a841-11eb-9650-dcc55903b236.png)

@sheetalj2205 something like this in left or right whichever suits more.

**Comment by sheetalj2205** [comment]
Okay! I will work on this.

**Comment by msk4862** [comment]
@sheetalj2205 Go ahead

**Comment by sheetalj2205** [comment]
![bg](https://user-images.githubusercontent.com/64475191/117019587-2a43c380-ad13-11eb-9bf2-aad98c537c36.JPG)
![bug](https://user-images.githubusercontent.com/64475191/117019595-2c0d8700-ad13-11eb-8491-04fdd4a3669f.JPG)

I am getting this problem on committing.

**Comment by msk4862** [comment]
@sheetalj2205 Have you done any changes in `AboutUs.jsx` file?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Have you done any changes in `AboutUs.jsx` file?

Yes because I am inserting sidebar in that

**Comment by msk4862** [comment]
@sheetalj2205 I think you maybe be missing a `aria-label` attribute in button or icon. Use [this](https://stackoverflow.com/questions/58367013/a-control-must-be-associated-with-a-text-label) for reference.

**Comment by msk4862** [comment]
@sheetalj2205 any updates?
