### ISSUE TITLE
"Top" button is not visible properly

### ISSUE THREAD

**Issue by Fpj-11** [CodeTrophs/Frontend#312]
**Is your feature request related to a problem? Please describe.**
"Top" button at the bottom right corner is not visible properly. It would be better if we change its color to make it visible

**Describe the solution you'd like**
Can put some icon pointing towards the top.

**Describe alternatives you've considered**

**Additional context**
![Screenshot (2094)](https://user-images.githubusercontent.com/76908206/113753034-4449b080-972b-11eb-859d-b1fcec39f4cd.png)

**Comment by Fpj-11** [comment]
I am interested in front-end development. Kindly assign this issue to me.

**Comment by aryasoni98** [comment]
@Fpj-11 Go Head.

**Comment by neha07kumari** [comment]
@aryasoni98  Can you please assign me this issue . I want to work on it.
