### ISSUE TITLE
Testimonial Navigation Buttons misaligned wrt the Image Below them

### ISSUE THREAD

**Issue by N-Shar-ma** [CodeTrophs/Frontend#314]
## Bug

The next and previous buttons in the Testimonials section on the homepage are not well aligned with the image below them in large screen view

### To Reproduce

- Go to `https://codetrophs.io/` on a laptop / desktop
- Scroll down to the testimonials section

## Expected Behaviour
The buttons should be aligned with the left and right edges of the image below them

## Screenshots of now
![image](https://user-images.githubusercontent.com/68962290/113930810-9da2f580-97a6-11eb-8988-b5729d8e66a5.png)

## Screenshots of my Proposed Solution
![image](https://user-images.githubusercontent.com/68962290/113930921-bca18780-97a6-11eb-80e6-ec50acdb8ba6.png)

**Desktop**
 - OS: Windows
 - Browser: Edge
 - Version: Latest

If you approve of this change, I would love to fix this bug under GSSoC'21

**Comment by aryasoni98** [comment]
@N-Shar-ma Go Head
