### ISSUE TITLE
UI improvement Icons in Footer

### ISSUE THREAD

**Issue by tanishq-arya** [CodeTrophs/Frontend#315]
**Describe the bug**

1. Adding hover to social icons in footer
2. The links open in same tab 

**To Reproduce**

Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aryasoni98** [comment]
Check the issue #302
