### ISSUE TITLE
UI Back to top button is not visible clearly

### ISSUE THREAD

**Issue by tanishq-arya** [CodeTrophs/Frontend#316]
**Describe the bug**

The button is not clearly visible and I for once missed it too.
I would like to modify the css for the same  

**To Reproduce**

Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aryasoni98** [comment]
Check the issue #312
