### ISSUE TITLE
improving ui of testimonials

### ISSUE THREAD

**Issue by shonali2600** [CodeTrophs/Frontend#318]
**Is your feature request related to a problem? Please describe.**

UI of testimonial is not looking good.

**Describe the solution you'd like**

I would like to improve its appearance

please assign this to me as a gssoc participant

**Comment by kumar-tushar** [comment]
@irshadjsr21 Want to work on this issue.
The UI is very traditional for the testimonial.
I want to place the left-right navigation button on the left and right side of the screen respectively and the content of the testimonial in the center so that the quote and photo are horizontal aligned.

**Comment by shonali2600** [comment]
@kumar-tushar I've created this issue because I want to work on this issue, Please try to search any other issue or create other

**Comment by aryasoni98** [comment]
@shonali2600 Go Head

**Comment by shonali2600** [comment]
@aryasoni98  the label "gssoc2021" is not valid, please change it to the valid label. ex: gssoc21

**Comment by aryasoni98** [comment]
@shonali2600 Okay .
