### ISSUE TITLE
Align Footer content in Center in MOBILE VIEW

### ISSUE THREAD

**Issue by kumar-tushar** [CodeTrophs/Frontend#319]
![Screenshot_2021-04-10-15-40-56-084_com android chrome](https://user-images.githubusercontent.com/56949668/114266371-9df3f880-9a13-11eb-9a02-c8f509294bf1.jpg)

It will look nice if the text content of Footer is in the Center when you are on Mobile View.

@irshadjsr21 Want to fix this issue!

**Comment by aryasoni98** [comment]
@kumar-tushar Go Head
