### ISSUE TITLE
Not responsive for iPad 

### ISSUE THREAD

**Issue by sheetalj2205** [CodeTrophs/Frontend#328]
**Describe the bug**
Home page is not responsive for iPad screen

**To Reproduce**

Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aryasoni98** [comment]
@sheetalj2205 Go Head

**Comment by msk4862** [comment]
@sheetalj2205 what's the progress?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 what's the progress?
waiting for my previous PR to get merged. I have solved this problem

**Comment by Anurag5086** [comment]
@sheetalj2205 What's the progress?

**Comment by sheetalj2205** [comment]
> @sheetalj2205 What's the progress?

my PR got merged but they haven't given me a label.

**Comment by msk4862** [comment]
@sheetalj2205 Any updates?

**Comment by sheetalj2205** [comment]
I am working on this issue but when I run the project I am getting this error.
![bug](https://user-images.githubusercontent.com/64475191/116203409-4a92e180-a759-11eb-9f57-012f0be41dc5.JPG)
Please fix this so I can complete this bug.

**Comment by msk4862** [comment]
@sheetalj2205 try running `npm install`
