### ISSUE TITLE
fix the navbar

### ISSUE THREAD

**Issue by Anurag5086** [CodeTrophs/Frontend#331]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behaviour:
1. Login
2. Look at the Navbar
3. See error

**Error**
![image](https://user-images.githubusercontent.com/54763478/115111532-df475380-9f91-11eb-9a57-15743bf0660f.png)

**Expected**
![image](https://user-images.githubusercontent.com/54763478/115111501-c343b200-9f91-11eb-8662-d4e50f0bb7db.png)

**Screenshots**

**Comment by Sristi27** [comment]
Hello there, I am a Gssoc Participant.Kindly assign this issue to me

**Comment by aryasoni98** [comment]
@Sristi27 Go Head 👍🏻

**Comment by Anurag5086** [comment]
@Sristi27 What's the update?

**Comment by srrathi** [comment]
@Anurag5086 Can you please assign this issue to me i've already solved some of it.
![Screenshot_2021-04-29 React App](https://user-images.githubusercontent.com/57089237/116476993-a2386680-a899-11eb-9f00-4b7b4b323fde.png)

**Comment by aryasoni98** [comment]
@Sristi27 Any update ? | @srrathi Go Head

**Comment by srrathi** [comment]
I want to ask do we need About us, Privacy Policy and T&C in navbar of pages other than landing.
![image](https://user-images.githubusercontent.com/57089237/116564292-77462500-a922-11eb-815c-81c68bc04c23.png)

**Comment by srrathi** [comment]
@aryasoni98 I need some help so that i can move forward in resolving this issue.

**Comment by srrathi** [comment]
@aryasoni98 I've fixed the navbar. Please have a look at it. If it's correct I'll send the PR.
![image](https://user-images.githubusercontent.com/57089237/116770406-5d5f2c00-aa61-11eb-8917-893f847bf032.png)

**Comment by msk4862** [comment]
@srrathi Yes, go ahead create a PR.

**Comment by srrathi** [comment]
Okk I'll Send PR by today.

**Comment by srrathi** [comment]
@aryasoni98 @msk4862 I've raised PR regarding it [PR #351](https://github.com/CodeTrophs/Frontend/pull/351). Please review and merge it.

**Comment by srrathi** [comment]
I'm sorry things got a bit messy in previous PR. I've raised a new PR resolving all the issues for this. Its [PR #353](https://github.com/CodeTrophs/Frontend/pull/353)
