### ISSUE TITLE
error  'goToPrevious' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by aryasoni98** [CodeTrophs/Frontend#340]
**Describe the bug**
Node CI Action Error `npm run lint`
> codetrophs@1.0.0 lint /home/runner/work/Frontend/Frontend
> eslint src/**/* pages/**/* --ext .jsx,.js --fix
/home/runner/work/Frontend/Frontend/src/components/Carousel.jsx
Error:   16:12  error  'goToPrevious' is defined but never used  no-unused-vars

**Screenshots**

<img width="1667" alt="Screenshot 2021-04-23 at 9 19 48 PM" src="https://user-images.githubusercontent.com/18515597/115897467-14fca880-a47a-11eb-83c8-04ea3214ec97.png">

**Comment by jonathanalvares9009** [comment]
Can I work on this issue?

**Comment by aryasoni98** [comment]
Yes sure, Go Head @jonathanalvares9009

**Comment by jonathanalvares9009** [comment]
@aryasoni98 delete the function or will it be used in the future

**Comment by msk4862** [comment]
@jonathanalvares9009 Just commenting it out will be better I think.

**Comment by jonathanalvares9009** [comment]
Ok
