### ISSUE TITLE
minor fixes on homepage

### ISSUE THREAD

**Issue by Anurag5086** [CodeTrophs/Frontend#349]
## 1. Center the Donate us Button.

![image](https://user-images.githubusercontent.com/54763478/116455590-4dcdc080-a872-11eb-8abe-7bd0a1cd39db.png)

## 2. Add a bottom margin to the testimonial component.

![image](https://user-images.githubusercontent.com/54763478/116455746-7f468c00-a872-11eb-9dc5-7b89690e770e.png)

**Comment by srrathi** [comment]
I've resolved this issue please assign it to me @Anurag5086 
![Screenshot_2021-04-29 CodeTrophs - A one spot Destination for your CodeTrophs Contribution Journey](https://user-images.githubusercontent.com/57089237/116478784-41f6f400-a89c-11eb-92ee-981c4e43d765.png)

**Comment by Anurag5086** [comment]
@srrathi Cool! Assigned.

**Comment by srrathi** [comment]
I've resolved the button issue but the testimonial section is looking fine on my machine. You can see it.
![image](https://user-images.githubusercontent.com/57089237/116562705-06ead400-a921-11eb-935a-967340e778ff.png)

**Comment by Anurag5086** [comment]
> @Anurag5086 I've resolved the button issue but the testimonial section is looking fine on my machine. You can see it. Should I send the PR.
> ![Screenshot_2021-04-29 CodeTrophs - A one spot Destination for your CodeTrophs Contribution Journey(1)](https://user-images.githubusercontent.com/57089237/116563162-66e17a80-a921-11eb-9bbd-ed7287e2be6b.png)

Sure make a PR.

**Comment by srrathi** [comment]
okk I'll make one by EOD.

**Comment by srrathi** [comment]
@Anurag5086 I've raised a PR solving this issue. Please merge it. You can see it [PR #352](https://github.com/CodeTrophs/Frontend/pull/352)

**Comment by Anurag5086** [comment]
> @Anurag5086 I've raised a PR solving this issue. Please merge it. You can see it [PR #352](https://github.com/CodeTrophs/Frontend/pull/352)

Sure!

**Comment by srrathi** [comment]
@Anurag5086 @aryasoni98 @msk4862 I'm sorry the previous PR got some messy, I've raised a new one [PR #354](https://github.com/CodeTrophs/Frontend/pull/354) You can review it.
