### ISSUE TITLE
To add About us, Privacy Policy and T&C in footer rather than in header of all pages other than landing.

### ISSUE THREAD

**Issue by srrathi** [CodeTrophs/Frontend#350]
**Is your feature request related to a problem? Please describe.**

The navabr is not looking fine with About us, Privacy Policy and T&C in it.

**Describe the solution you'd like**

We can add them in the footer and can make a seperate section for them in the footer which will look much clean.
**Describe alternatives you've considered**

**Additional context**

**Comment by srrathi** [comment]
If you agree with it please do consider assigning this issue to me.

**Comment by aryasoni98** [comment]
@srrathi  Sure, Go Head

**Comment by srrathi** [comment]
@aryasoni98 I need some help regarding the placement of these three in the footer. I mean help in the design part how you want it to look like or do you have any design suggestion for it. What I'm thinking is to make 3 columns in footer first column will contain these important links, second column will contain any office address and contact info like mail if we have them and third column will contain the social links. What you suggest?

**Comment by srrathi** [comment]
Is it Okay @aryasoni98 @Anurag5086 
![image](https://user-images.githubusercontent.com/57089237/116811211-aac4c180-ab65-11eb-8942-501906dbdded.png)

**Comment by aryasoni98** [comment]
@srrathi So wait I will send u the footer design

**Comment by aryasoni98** [comment]
Please update the last line of the footer to the given UI. Place about us, terms, and policy in one line and copyright to the next line. Both the line should be center-aligned.

![1](https://user-images.githubusercontent.com/18515597/116814928-cdaca100-ab78-11eb-9f68-91e394079772.jpeg)
 
**Like this**  @srrathi

**Comment by srrathi** [comment]
@aryasoni98 I'm not able to see any image on my github account. I've messaged you on Discord can you please send me this design there.

**Comment by srrathi** [comment]
@aryasoni98 Is it Fine. Should I send the PR.
![image](https://user-images.githubusercontent.com/57089237/116929290-d6d26680-ac7b-11eb-9d56-f7b8f8da9c7f.png)
![image](https://user-images.githubusercontent.com/57089237/116929357-eea9ea80-ac7b-11eb-94af-be2b190e200f.png)

**Comment by aryasoni98** [comment]
Yes sure @srrathi But icon should be centre in mobile view .

**Comment by srrathi** [comment]
> Yes sure @srrathi But icon should be centre in mobile view .

okay will do that and send PR by EOD.

**Comment by srrathi** [comment]
@aryasoni98 Is it okk Now. Should I send the PR.
![image](https://user-images.githubusercontent.com/57089237/117164933-afe27480-ade2-11eb-8b2c-71704e4d6f94.png)
![image](https://user-images.githubusercontent.com/57089237/117164848-9fca9500-ade2-11eb-9148-61b06a0162c0.png)

**Comment by aryasoni98** [comment]
@srrathi  Yes Sure.
